# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diceForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(718, 727)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setFocusPolicy(QtCore.Qt.WheelFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color:brown")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_welcome = QtWidgets.QLabel(self.centralwidget)
        self.lbl_welcome.setGeometry(QtCore.QRect(10, -10, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_welcome.setFont(font)
        self.lbl_welcome.setObjectName("lbl_welcome")
        self.lbl_image = QtWidgets.QLabel(self.centralwidget)
        self.lbl_image.setGeometry(QtCore.QRect(10, 40, 411, 121))
        self.lbl_image.setText("")
        self.lbl_image.setPixmap(QtGui.QPixmap("dice_win.jpg"))
        self.lbl_image.setObjectName("lbl_image")
        self.lbl_useDice = QtWidgets.QLabel(self.centralwidget)
        self.lbl_useDice.setGeometry(QtCore.QRect(10, 190, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_useDice.setFont(font)
        self.lbl_useDice.setObjectName("lbl_useDice")
        self.btn_roll = QtWidgets.QPushButton(self.centralwidget)
        self.btn_roll.setGeometry(QtCore.QRect(530, 170, 141, 41))
        self.btn_roll.setObjectName("btn_roll")
        self.lbl_gif = QtWidgets.QLabel(self.centralwidget)
        self.lbl_gif.setGeometry(QtCore.QRect(430, 40, 251, 121))
        self.lbl_gif.setText("")
        self.lbl_gif.setObjectName("lbl_gif")
        self.lbl_dice1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_dice1.setGeometry(QtCore.QRect(10, 260, 311, 251))
        self.lbl_dice1.setText("")
        self.lbl_dice1.setObjectName("lbl_dice1")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(270, 170, 251, 81))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.rb1 = QtWidgets.QRadioButton(self.groupBox)
        self.rb1.setGeometry(QtCore.QRect(10, 30, 51, 17))
        self.rb1.setObjectName("rb1")
        self.rb2 = QtWidgets.QRadioButton(self.groupBox)
        self.rb2.setGeometry(QtCore.QRect(100, 30, 51, 17))
        self.rb2.setObjectName("rb2")
        self.rb3 = QtWidgets.QRadioButton(self.groupBox)
        self.rb3.setGeometry(QtCore.QRect(190, 30, 51, 17))
        self.rb3.setObjectName("rb3")
        self.lbl_dice2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_dice2.setGeometry(QtCore.QRect(330, 260, 321, 251))
        self.lbl_dice2.setText("")
        self.lbl_dice2.setObjectName("lbl_dice2")
        self.lbl_dice3 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_dice3.setGeometry(QtCore.QRect(170, 520, 441, 171))
        self.lbl_dice3.setText("")
        self.lbl_dice3.setObjectName("lbl_dice3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 718, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_welcome.setText(_translate("MainWindow", "Welcome to the dice game"))
        self.lbl_useDice.setText(_translate("MainWindow", "Choose the number of dice you want to use:"))
        self.btn_roll.setText(_translate("MainWindow", "Roll"))
        self.rb1.setText(_translate("MainWindow", "1"))
        self.rb2.setText(_translate("MainWindow", "2"))
        self.rb3.setText(_translate("MainWindow", "3"))
