# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'check_hobby.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(639, 457)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_secilenleriAl = QtWidgets.QPushButton(self.centralwidget)
        self.btn_secilenleriAl.setGeometry(QtCore.QRect(100, 270, 75, 23))
        self.btn_secilenleriAl.setObjectName("btn_secilenleriAl")
        self.lbl_result = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result.setGeometry(QtCore.QRect(420, 70, 191, 191))
        self.lbl_result.setText("")
        self.lbl_result.setObjectName("lbl_result")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(100, 74, 171, 191))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cinema_check = QtWidgets.QCheckBox(self.widget)
        self.cinema_check.setObjectName("cinema_check")
        self.verticalLayout.addWidget(self.cinema_check)
        self.book_check = QtWidgets.QCheckBox(self.widget)
        self.book_check.setObjectName("book_check")
        self.verticalLayout.addWidget(self.book_check)
        self.sport_check = QtWidgets.QCheckBox(self.widget)
        self.sport_check.setObjectName("sport_check")
        self.verticalLayout.addWidget(self.sport_check)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 639, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_secilenleriAl.setText(_translate("MainWindow", "Seçilenleri Al"))
        self.cinema_check.setText(_translate("MainWindow", "Sinema"))
        self.book_check.setText(_translate("MainWindow", "Kitap Okumak"))
        self.sport_check.setText(_translate("MainWindow", "Spor"))
